/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package search;

import mylibrary.BookJDialog;
import search.TitleJFrame;
import search.GenreJDialog;
import search.AuthorJFrame;

/**
 *
 * @author Jonathan
 */
public class SearchJDialog extends javax.swing.JDialog {

    /**
     * Creates new form EnterJDialog
     */
    public SearchJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BookTitleButton = new javax.swing.JButton();
        ClearFormButton = new javax.swing.JButton();
        HomeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        GenreButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("My Library Search");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MY LIBRARY BOOK SEARCH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 0, 308, 51));

        jLabel2.setText("© Creative Native Coding");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 460, -1, 14));

        BookTitleButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        BookTitleButton.setText("BOOK TITLE");
        BookTitleButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        BookTitleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookTitleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BookTitleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 126, 136, 47));

        ClearFormButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        ClearFormButton.setText("AUTHOR");
        ClearFormButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        ClearFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFormButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearFormButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 181, 136, 47));

        HomeButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        HomeButton.setText("HOME");
        HomeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));
        HomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(HomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 287, 136, 47));

        jLabel3.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SEARCH BY:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 57, 308, 51));

        GenreButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        GenreButton.setText("GENRE");
        GenreButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        GenreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenreButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GenreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 234, 136, 47));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BookTitleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookTitleButtonActionPerformed
        TitleJFrame.main(null);   // open title search form
        this.dispose(); //Close this one
    }//GEN-LAST:event_BookTitleButtonActionPerformed

    private void HomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeButtonActionPerformed
        // Return User to Main form
        BookJDialog.main(null);   // open main form
        this.dispose(); //Close this one
    }//GEN-LAST:event_HomeButtonActionPerformed

    private void ClearFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFormButtonActionPerformed
         AuthorJFrame.main(null);   // open Author Form
         this.dispose(); //Close this one
    }//GEN-LAST:event_ClearFormButtonActionPerformed

    private void GenreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenreButtonActionPerformed
         GenreJDialog.main(null);   // open my second class
         this.dispose(); //Close this one
    }//GEN-LAST:event_GenreButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                SearchJDialog dialog = new SearchJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookTitleButton;
    private javax.swing.JButton ClearFormButton;
    private javax.swing.JButton GenreButton;
    private javax.swing.JButton HomeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
