/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package search;

import ConnectionManager.dbConnectionManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jonathan
 */
public class TitleJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TitleJFrame
     */
    public TitleJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchHomeButton = new javax.swing.JButton();
        listButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        listAllButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        titleTable = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Library Title Search");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchHomeButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        searchHomeButton.setText("Search Home");
        searchHomeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        searchHomeButton.setPreferredSize(new java.awt.Dimension(101, 33));
        searchHomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchHomeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchHomeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 272, 185, 42));

        listButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        listButton.setText("List Books");
        listButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        listButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listButtonActionPerformed(evt);
            }
        });
        getContentPane().add(listButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 152, 185, 42));

        clearButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        clearButton.setText("Clear");
        clearButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 212, 185, 42));

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SEARCH BY TITLE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 12, 381, 51));

        jLabel2.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        jLabel2.setText("Book Title:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(158, 92, -1, 54));

        titleTextField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(titleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 106, 317, -1));

        jLabel4.setText("© Creative Native Coding");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(595, 577, 145, 34));

        listAllButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        listAllButton.setText("List All");
        listAllButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        listAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listAllButtonActionPerformed(evt);
            }
        });
        getContentPane().add(listAllButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 152, 185, 42));

        titleTable.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEtchedBorder(), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        titleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(titleTable);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 710, 169));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void titleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleTextFieldActionPerformed

    private void searchHomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchHomeButtonActionPerformed
        SearchJDialog.main(null);   // open main search form
        this.dispose(); //Close this one
    }//GEN-LAST:event_searchHomeButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        titleTextField.setText("");
        ((DefaultTableModel) titleTable.getModel()).setRowCount(0);
        titleTextField.requestFocus();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void listButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listButtonActionPerformed
        // TODO add your handling code here:
        String title = titleTextField.getText();
        if ("".equals(titleTextField.getText())) {
            JOptionPane.showMessageDialog(null, "Please Enter A BOOK TITLE!");
        } else {
            String sql = String.format("SELECT * FROM book where Title = " + "'" + title + "'");

            if (sql != null && sql.trim().length() > 0) {
                DefaultTableModel tableModel = new DefaultTableModel();

                try {

                    dbConnectionManager.getConnection();

                    java.sql.Statement stmt = dbConnectionManager.getConnection().prepareStatement(sql);
                    stmt.executeQuery(sql);
                    try (ResultSet rs = stmt.getResultSet()) {
                        ResultSetMetaData rsMeta = rs.getMetaData();
                        int colCount = rsMeta.getColumnCount();
                        for (int i = 1; i <= colCount; i++) {
                            tableModel.addColumn(rsMeta.getColumnLabel(i));
                        }
                        while (rs.next()) {
                            String[] rowData = new String[colCount];

                            for (int i = 1; i <= rowData.length; i++) {
                                String colLabel = rsMeta.getColumnLabel(i);
                                String colValue = rs.getString(colLabel);
                                rowData[i - 1] = colValue;
                            }
                            tableModel.addRow(rowData);
                        }
                        titleTable.setModel(tableModel);
                        titleTextField.setText("");
                        titleTextField.requestFocus();
                        dbConnectionManager.getConnection().close();
                    }

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_listButtonActionPerformed

    private void listAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listAllButtonActionPerformed
        // TODO add your handling code here:
        String sql = String.format("SELECT * FROM book");

        if (sql != null && sql.trim().length() > 0) {
            DefaultTableModel tableModel = new DefaultTableModel();

            try {

                dbConnectionManager.getConnection();

                java.sql.Statement stmt = dbConnectionManager.getConnection().prepareStatement(sql);
                stmt.executeQuery(sql);
                try (ResultSet rs = stmt.getResultSet()) {
                    ResultSetMetaData rsMeta = rs.getMetaData();
                    int colCount = rsMeta.getColumnCount();
                    for (int i = 1; i <= colCount; i++) {
                        tableModel.addColumn(rsMeta.getColumnLabel(i));
                    }
                    while (rs.next()) {
                        String[] rowData = new String[colCount];

                        for (int i = 1; i <= rowData.length; i++) {
                            String colLabel = rsMeta.getColumnLabel(i);
                            String colValue = rs.getString(colLabel);
                            rowData[i - 1] = colValue;
                        }
                        tableModel.addRow(rowData);
                    }
                    titleTable.setModel(tableModel);
                }

            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_listAllButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TitleJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton listAllButton;
    private javax.swing.JButton listButton;
    private javax.swing.JButton searchHomeButton;
    private javax.swing.JTable titleTable;
    private javax.swing.JTextField titleTextField;
    // End of variables declaration//GEN-END:variables
}
