/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mylibrary;

import ConnectionManager.dbConnectionManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonathan
 */
public class EnterJDialog extends javax.swing.JDialog {

    /**
     * Creates new form EnterJDialog
     *
     * @param parent
     * @param modal
     */
    public EnterJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    EnterJDialog() {
        throw new UnsupportedOperationException("Not yet implemented");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TitleTextField = new javax.swing.JTextField();
        ANameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        GenreField = new javax.swing.JTextField();
        EnterBookButton = new javax.swing.JButton();
        ClearFormButton = new javax.swing.JButton();
        homeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MessagePane = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("My Library Book Entry");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Freestyle Script", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MY LIBRARY BOOK ENTRY");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 308, 51));

        jLabel2.setText("© Creative Native Coding");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 438, -1, 14));

        jLabel3.setText("Book Title:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 103, -1, -1));

        TitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });
        getContentPane().add(TitleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 99, 141, 25));
        getContentPane().add(ANameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 134, 141, 25));

        jLabel4.setText("Author  Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 138, -1, -1));

        jLabel5.setText("Genre:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 174, -1, -1));
        getContentPane().add(GenreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 170, 141, 25));

        EnterBookButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        EnterBookButton.setText("Enter Book");
        EnterBookButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        EnterBookButton.setPreferredSize(new java.awt.Dimension(101, 33));
        EnterBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterBookButtonActionPerformed(evt);
            }
        });
        getContentPane().add(EnterBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 303, 136, 47));

        ClearFormButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        ClearFormButton.setText("Clear Form");
        ClearFormButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        ClearFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFormButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ClearFormButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 362, 136, 47));

        homeButton.setFont(new java.awt.Font("Freestyle Script", 0, 24)); // NOI18N
        homeButton.setText("Home");
        homeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, java.awt.Color.black));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 238, 136, 47));

        MessagePane.setEditable(false);
        jScrollPane1.setViewportView(MessagePane);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 421, 294, -1));

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("* REQUIRED FIELD");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 200, -1, -1));

        jLabel7.setForeground(new java.awt.Color(204, 0, 0));
        jLabel7.setText("*");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 103, -1, -1));

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("*");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 138, -1, -1));

        jLabel9.setForeground(new java.awt.Color(204, 0, 0));
        jLabel9.setText("*");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 174, -1, -1));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Help");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none


    private void EnterBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterBookButtonActionPerformed
        // Enter Book info Into Database

        if (("".equals(TitleTextField.getText())) || ("".equals(ANameField.getText())) || ("".equals(GenreField.getText()))) {
            JOptionPane.showMessageDialog(null, "You have forgotten one or more required fields");
        } else {
            try {

                dbConnectionManager.getConnection();

                String Title = TitleTextField.getText();
                String AuthorName = ANameField.getText() ;
                String BookGenre = GenreField.getText();
                String BookStatus = "In";

//                java.sql.Statement stmt = dbConnectionManager.getConnection().createStatement();
                String sql = String.format("INSERT INTO book (Title, AuthorName, Genre, BookStatus) VALUES ('" +  Title + "','" +  AuthorName + "','" +  BookGenre + "','" +  BookStatus + "')");
                java.sql.Statement stmt = dbConnectionManager.getConnection().prepareStatement(sql);
                stmt.executeUpdate(sql);
                
                //Display Success Message
                MessagePane.setText(TitleTextField.getText() + " entered successfully!");

                // Clear All Form Fields
                TitleTextField.setText("");
                ANameField.setText("");
                GenreField.setText("");
                TitleTextField.requestFocus();
                dbConnectionManager.getConnection().close();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }

    }//GEN-LAST:event_EnterBookButtonActionPerformed

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeButtonActionPerformed
        //Open Main Form Close this one
        BookJDialog.main(null);   // open my second class
        this.dispose(); //Close this one
    }//GEN-LAST:event_homeButtonActionPerformed

    private void ClearFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFormButtonActionPerformed
        // Clear All Form Fields
        TitleTextField.setText("");
        ANameField.setText("");
        GenreField.setText("");
        TitleTextField.requestFocus();

    }//GEN-LAST:event_ClearFormButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EnterJDialog dialog = new EnterJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ANameField;
    private javax.swing.JButton ClearFormButton;
    private javax.swing.JButton EnterBookButton;
    private javax.swing.JTextField GenreField;
    private javax.swing.JTextPane MessagePane;
    private javax.swing.JTextField TitleTextField;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
